<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>A reanalysis of ‘Infants’ Domain-General Responses to Expectancy Violations’</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="domain_general_voe_reanalysis_files/libs/clipboard/clipboard.min.js"></script>
<script src="domain_general_voe_reanalysis_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="domain_general_voe_reanalysis_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="domain_general_voe_reanalysis_files/libs/quarto-html/popper.min.js"></script>
<script src="domain_general_voe_reanalysis_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="domain_general_voe_reanalysis_files/libs/quarto-html/anchor.min.js"></script>
<link href="domain_general_voe_reanalysis_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="domain_general_voe_reanalysis_files/libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="domain_general_voe_reanalysis_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="domain_general_voe_reanalysis_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="domain_general_voe_reanalysis_files/libs/bootstrap/bootstrap-138a6193a3bd40baf1e627da441a4734.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="99">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#observation-1-trial-order-expected-first-or-unexpected-first-has-a-very-large-effect-on-looking-time" id="toc-observation-1-trial-order-expected-first-or-unexpected-first-has-a-very-large-effect-on-looking-time" class="nav-link" data-scroll-target="#observation-1-trial-order-expected-first-or-unexpected-first-has-a-very-large-effect-on-looking-time">Observation: 1 Trial order (expected first or unexpected first) has a very large effect on looking time</a>
  <ul class="collapse">
  <li><a href="#trial-order-effect-by-task" id="toc-trial-order-effect-by-task" class="nav-link" data-scroll-target="#trial-order-effect-by-task">Trial Order Effect (by task)</a></li>
  <li><a href="#trial-order-effect-overall" id="toc-trial-order-effect-overall" class="nav-link" data-scroll-target="#trial-order-effect-overall">Trial Order Effect (overall)</a></li>
  </ul></li>
  <li><a href="#observation-2-the-latent-factor-in-the-cfa-appears-mostly-if-not-entirely-to-be-capturing-variation-due-to-assigned-order." id="toc-observation-2-the-latent-factor-in-the-cfa-appears-mostly-if-not-entirely-to-be-capturing-variation-due-to-assigned-order." class="nav-link" data-scroll-target="#observation-2-the-latent-factor-in-the-cfa-appears-mostly-if-not-entirely-to-be-capturing-variation-due-to-assigned-order.">Observation 2: The latent factor in the CFA appears mostly (if not entirely) to be capturing variation due to assigned order.</a>
  <ul class="collapse">
  <li><a href="#original-single-factor-model" id="toc-original-single-factor-model" class="nav-link" data-scroll-target="#original-single-factor-model">0. Original (Single-Factor) Model</a></li>
  <li><a href="#mimic-model" id="toc-mimic-model" class="nav-link" data-scroll-target="#mimic-model">1. MIMIC model</a></li>
  <li><a href="#residualized-model" id="toc-residualized-model" class="nav-link" data-scroll-target="#residualized-model">2. Residualized model</a></li>
  <li><a href="#predicting-estimated-latent-scores-from-outcome-order" id="toc-predicting-estimated-latent-scores-from-outcome-order" class="nav-link" data-scroll-target="#predicting-estimated-latent-scores-from-outcome-order">3. Predicting estimated latent scores from outcome order</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  </ul></li>
  <li><a href="#observation-3-correlations-do-not-generally-hold-when-outcome-order-is-taken-into-account" id="toc-observation-3-correlations-do-not-generally-hold-when-outcome-order-is-taken-into-account" class="nav-link" data-scroll-target="#observation-3-correlations-do-not-generally-hold-when-outcome-order-is-taken-into-account">Observation 3: Correlations do not generally hold when outcome order is taken into account</a>
  <ul class="collapse">
  <li><a href="#original-correlations" id="toc-original-correlations" class="nav-link" data-scroll-target="#original-correlations">Original Correlations</a></li>
  <li><a href="#correlations-split-by-outcome-order" id="toc-correlations-split-by-outcome-order" class="nav-link" data-scroll-target="#correlations-split-by-outcome-order">Correlations split by outcome order</a></li>
  <li><a href="#no-significant-effect-after-controlling-for-outcome-order" id="toc-no-significant-effect-after-controlling-for-outcome-order" class="nav-link" data-scroll-target="#no-significant-effect-after-controlling-for-outcome-order">No significant effect after controlling for outcome order</a></li>
  </ul></li>
  <li><a href="#other-concerns" id="toc-other-concerns" class="nav-link" data-scroll-target="#other-concerns">Other concerns</a>
  <ul class="collapse">
  <li><a href="#only-2-of-the-8-voe-tasks-show-a-significant-voe-effect" id="toc-only-2-of-the-8-voe-tasks-show-a-significant-voe-effect" class="nav-link" data-scroll-target="#only-2-of-the-8-voe-tasks-show-a-significant-voe-effect">Only 2 of the 8 VOE tasks show a significant VOE effect</a></li>
  <li><a href="#bayesian-model-issues" id="toc-bayesian-model-issues" class="nav-link" data-scroll-target="#bayesian-model-issues">Bayesian model issues</a>
  <ul class="collapse">
  <li><a href="#interpretation-of-interaction-as-a-main-effect" id="toc-interpretation-of-interaction-as-a-main-effect" class="nav-link" data-scroll-target="#interpretation-of-interaction-as-a-main-effect">Interpretation of interaction as a main effect</a></li>
  <li><a href="#interaction-model-does-not-include-lower-order-effects" id="toc-interaction-model-does-not-include-lower-order-effects" class="nav-link" data-scroll-target="#interaction-model-does-not-include-lower-order-effects">Interaction Model does not include lower-order effects</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">A reanalysis of ‘Infants’ Domain-General Responses to Expectancy Violations’</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>This is a reanalysis of Bisbee &amp; Feigenson (2026), focusing on the fact that infants were not randomly assigned to <em>always</em> either see surprising outcomes first (for all 8 VOE events) or <em>always</em> see unexpected outcomes. This has important consequences for the interpretation of individual differences in the paper. The upshot is that what are interpreted as individual differences in the paper are mostly measurements of whether infants were assigned to see surprising outcomes first or expected outcomes first: Infants who saw surprising test trials first look longer to surprising events, infants who saw expected test trials first tend to look longer at expected events, and this explains most of the systematic variance across individuals. In other words, variation in looking time differences is explained by order effects.</p>
</section>
<section id="setup" class="level1">
<h1>Setup</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lavaan)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(cowplot)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(effectsize)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(RColorBrewer)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>This setup code chunk just follows the code (helpfully shared) from the original paper, reading in the primary VOE data and applying exclusion criteria and transformations from the paper.</p>
<p>First, I add a chunk adapted from the original code for processing the raw data into the primary data for analysis. Download the raw_voe_data.csv file from the OSF repository and place it in the data folder to run this step. Or, skip it and move straight to the next chunk.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load raw frame-level dataset</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>raw_voe_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"raw_voe_data.csv"</span>))</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Aggregate to trial-level means for each subject/scene/outcome</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>primary_voe_data_intermediate <span class="ot">&lt;-</span> raw_voe_data <span class="sc">%&gt;%</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(subj, age_months, gender, eu_order, domain, scene, outcome, test) <span class="sc">%&gt;%</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">look =</span> <span class="fu">mean</span>(look, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">spread</span>(test, look) <span class="sc">%&gt;%</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">subject =</span> subj,</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    age_months,</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>    gender,</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">outcome_order =</span> eu_order,</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>    domain,</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">task =</span> scene,</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>    outcome,</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">familiarization =</span> fam,</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">test_window =</span> test</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a><span class="co">#save primary data file</span></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(primary_voe_data_intermediate, <span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"primary_voe_data_intermediate.csv"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Read in the intermediate data file and apply exclusion criteria from the paper (using code from the original paper’s code base, lightly modified to retain additional variables).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>primary_voe_data_intermediate <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"primary_voe_data_intermediate.csv"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 1350 Columns: 9
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (5): gender, outcome_order, domain, task, outcome
dbl (4): subject, age_months, familiarization, test_window

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Retain only trials where infants looked at least 50% of the familiarization phase</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>primary_voe_data_fam_excl <span class="ot">&lt;-</span> primary_voe_data_intermediate <span class="sc">%&gt;%</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(familiarization <span class="sc">&gt;</span> <span class="fl">0.5</span>) <span class="sc">%&gt;%</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span>familiarization)  <span class="co"># Drop column after filter</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute log-looking time to normalize skew and reduce influence of long looks</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="co"># - Trials must exceed 5s minimum looking time</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="co"># - Compute difference score: unexpected - expected</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>window_size_s <span class="ot">&lt;-</span> <span class="dv">30</span>                      <span class="co"># Freeze frame duration per test trial (in seconds)</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>minimum_looking_time <span class="ot">&lt;-</span> <span class="dv">5</span>                <span class="co"># Minimum threshold (in seconds)</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>primary_voe_data_look_excl <span class="ot">&lt;-</span> primary_voe_data_fam_excl <span class="sc">%&gt;%</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">look =</span> <span class="fu">log</span>(window_size_s <span class="sc">*</span> test_window),</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>         <span class="at">look_raw =</span> window_size_s <span class="sc">*</span> test_window) <span class="sc">%&gt;%</span> <span class="co">#edit here to preserve raw looking time</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span>test_window) <span class="sc">%&gt;%</span></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(look <span class="sc">&gt;</span> <span class="fu">log</span>(minimum_looking_time))  <span class="co"># Exclude very low-looking trials</span></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a><span class="co"># e. Compute difference between looking to unexpected and expected outcomes</span></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>primary_voe_data <span class="ot">&lt;-</span> primary_voe_data_look_excl <span class="sc">%&gt;%</span></span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>  <span class="co">#slight modification of original script: pivot both look and look_raw to wide format</span></span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> outcome, <span class="at">values_from =</span> <span class="fu">c</span>(look, look_raw)) <span class="sc">%&gt;%</span></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">diff_log =</span> look_unexpected <span class="sc">-</span> look_expected,</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">diff_raw =</span> look_raw_unexpected <span class="sc">-</span> look_raw_expected) <span class="sc">%&gt;%</span></span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>() <span class="sc">%&gt;%</span></span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="observation-1-trial-order-expected-first-or-unexpected-first-has-a-very-large-effect-on-looking-time" class="level1">
<h1>Observation: 1 Trial order (expected first or unexpected first) has a very large effect on looking time</h1>
<section id="trial-order-effect-by-task" class="level2">
<h2 class="anchored" data-anchor-id="trial-order-effect-by-task">Trial Order Effect (by task)</h2>
<p>The first descriptive thing to observe is just that expected first/ unexpected first has a large effect on the VOE effect: infants who (always) see expected events first look much longer to expected test trials (i.e., the first trial); infants who see unexpected events first look much longer to unexpected test trials. This is true for all events in the paper. This makes sense: we <em>should</em> expect infants (on average) to look much longer to the first test trial than the second (perceptually very similar) trial within a given VOE event. The analyses in the paper do not take this large source of between-infant variance into account.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">#summarize data for each VOE event by expected first vs. unexpected first</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>summarize_task_outcome_order <span class="ot">&lt;-</span> primary_voe_data <span class="sc">%&gt;%</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(domain,task, outcome_order) <span class="sc">%&gt;%</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_diff_log =</span> <span class="fu">mean</span>(diff_log),</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_diff_raw =</span> <span class="fu">mean</span>(diff_raw),</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    <span class="co">#95% CIs (quick approx)</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">ci_diff_log =</span> <span class="fl">1.96</span> <span class="sc">*</span> <span class="fu">sd</span>(diff_log) <span class="sc">/</span> <span class="fu">sqrt</span>(n),</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">ci_diff_raw =</span> <span class="fl">1.96</span> <span class="sc">*</span> <span class="fu">sd</span>(diff_raw) <span class="sc">/</span> <span class="fu">sqrt</span>(n),</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(summarize_task_outcome_order, <span class="fu">aes</span>(<span class="at">x =</span> outcome_order, <span class="at">y =</span> mean_diff_log, <span class="at">fill =</span> outcome_order,<span class="at">color=</span>outcome_order)) <span class="sc">+</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">data=</span>primary_voe_data,<span class="fu">aes</span>(<span class="at">y =</span> diff_log), <span class="at">width =</span> <span class="fl">0.1</span>,<span class="at">height=</span><span class="dv">0</span>, <span class="at">alpha =</span> <span class="fl">0.1</span>)<span class="sc">+</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> mean_diff_log <span class="sc">-</span> ci_diff_log, <span class="at">ymax =</span> mean_diff_log <span class="sc">+</span> ci_diff_log), <span class="at">width =</span> <span class="dv">0</span>, <span class="at">color=</span><span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> domain<span class="sc">+</span>task,<span class="at">ncol=</span><span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="co">#rename x-levels</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"exp_first"</span> <span class="ot">=</span> <span class="st">"Exp.</span><span class="sc">\n</span><span class="st">First"</span>, <span class="st">"unexp_first"</span> <span class="ot">=</span> <span class="st">"Unexp.</span><span class="sc">\n</span><span class="st">First"</span>)) <span class="sc">+</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Outcome Order"</span>,</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"VOE Effect (Unexpected - Expected Log Looking)"</span>) <span class="sc">+</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_cowplot</span>()<span class="sc">+</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position=</span><span class="st">"none"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="domain_general_voe_reanalysis_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="trial-order-effect-overall" class="level2">
<h2 class="anchored" data-anchor-id="trial-order-effect-overall">Trial Order Effect (overall)</h2>
<p>The plot above breaks this down by task, but just to emphasize that this effect is quite large, here’s a plot showing the effect summarizing across all VOE events, collapsing across domain and task.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" href="">Log Looking</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false" href="">Raw Looking</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co">#summarize data for each VOE event by expected first vs. unexpected first</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(summarize_order, <span class="fu">aes</span>(<span class="at">x =</span> outcome_order, <span class="at">y =</span> group_avg_diff_log, <span class="at">fill =</span> outcome_order,<span class="at">color=</span>outcome_order)) <span class="sc">+</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>(<span class="at">data=</span>summarize_subj_order,<span class="fu">aes</span>(<span class="at">y =</span> mean_diff_log),<span class="at">fill=</span><span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">data=</span>summarize_subj_order,<span class="fu">aes</span>(<span class="at">y =</span> mean_diff_log), <span class="at">width =</span> <span class="fl">0.1</span>,<span class="at">height=</span><span class="dv">0</span>, <span class="at">alpha =</span> <span class="fl">0.1</span>)<span class="sc">+</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size=</span><span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> group_avg_diff_log <span class="sc">-</span> ci_diff_log, <span class="at">ymax =</span> group_avg_diff_log <span class="sc">+</span> ci_diff_log), <span class="at">width =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"exp_first"</span> <span class="ot">=</span> <span class="st">"Expected First"</span>, <span class="st">"unexp_first"</span> <span class="ot">=</span> <span class="st">"Unexpected First"</span>)) <span class="sc">+</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Outcome Order"</span>,</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"VOE Effect (Unexpected - Expected Log Looking)"</span>) <span class="sc">+</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_cowplot</span>()<span class="sc">+</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position=</span><span class="st">"none"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="domain_general_voe_reanalysis_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co">#compute cohen's d</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cohens_d</span>(mean_diff_log <span class="sc">~</span> outcome_order, <span class="at">data =</span> summarize_subj_order)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cohen's d |         95% CI
--------------------------
-1.94     | [-2.45, -1.42]

- Estimated using pooled SD.</code></pre>
</div>
</div>
<p>The effect is extremely large, Cohen’s d = -1.94.</p>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co">#in raw looking time, just to have a feel</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(summarize_order, <span class="fu">aes</span>(<span class="at">x =</span> outcome_order, <span class="at">y =</span> group_avg_diff_raw, <span class="at">fill =</span> outcome_order,<span class="at">color=</span>outcome_order)) <span class="sc">+</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>(<span class="at">data=</span>summarize_subj_order,<span class="fu">aes</span>(<span class="at">y =</span> mean_diff_raw),<span class="at">fill=</span><span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">data=</span>summarize_subj_order,<span class="fu">aes</span>(<span class="at">y =</span> mean_diff_raw), <span class="at">width =</span> <span class="fl">0.1</span>,<span class="at">height=</span><span class="dv">0</span>, <span class="at">alpha =</span> <span class="fl">0.1</span>)<span class="sc">+</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size=</span><span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> group_avg_diff_raw <span class="sc">-</span> ci_diff_raw, <span class="at">ymax =</span> group_avg_diff_raw <span class="sc">+</span> ci_diff_raw), <span class="at">width =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"exp_first"</span> <span class="ot">=</span> <span class="st">"Expected First"</span>, <span class="st">"unexp_first"</span> <span class="ot">=</span> <span class="st">"Unexpected First"</span>)) <span class="sc">+</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Outcome Order"</span>,</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"VOE Effect (Unexpected - Expected Raw Looking)"</span>) <span class="sc">+</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_cowplot</span>()<span class="sc">+</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position=</span><span class="st">"none"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="domain_general_voe_reanalysis_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co">#compute cohen's d</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cohens_d</span>(mean_diff_raw <span class="sc">~</span> outcome_order, <span class="at">data =</span> summarize_subj_order)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cohen's d |         95% CI
--------------------------
-2.17     | [-2.70, -1.63]

- Estimated using pooled SD.</code></pre>
</div>
</div>
<p>The effect is extremely large, Cohen’s d = -2.17.</p>
</div>
</div>
</div>
</section>
</section>
<section id="observation-2-the-latent-factor-in-the-cfa-appears-mostly-if-not-entirely-to-be-capturing-variation-due-to-assigned-order." class="level1">
<h1>Observation 2: The latent factor in the CFA appears mostly (if not entirely) to be capturing variation due to assigned order.</h1>
<p>The core worry is that the single-factor emerging from the CFA analysis is mainly tracking whether infants were assigned to unexpected-first or expected-first orders (since this structures variation in looking time).</p>
<p>I first re-fit the original model, which revealed a latent, single factor underlying variation. I then pursue several different strategies to try to understand to what extent the latent factor (interpreted as a general surprise factor in the paper) is explained by the order confound. I tried a few different approaches here, because it’s not quite clear to me whether there was a “best” way to understand to what extent the latent factor is (just) an artifact of the order confound. <strong>Triangulating across these three approaches, it seems like the answer is yes: The latent factor is mostly if not entirely capturing variation due to assigned order.</strong></p>
<ol type="1">
<li><p>To what extent does assigned order explain variation in the latent factor (fitting a MIMIC model)?</p></li>
<li><p>Does a latent factor emerge after residualizing looking for each task on order?</p></li>
<li><p>Estimating individual scores for the latent variable and regressing them on outcome order (less good than the MIMIC model because of attenuation due to measurement reliability).</p></li>
</ol>
<section id="original-single-factor-model" class="level2">
<h2 class="anchored" data-anchor-id="original-single-factor-model">0. Original (Single-Factor) Model</h2>
<p>I can first reproduce the original model, using the code from the paper (great!).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>dat.lav <span class="ot">&lt;-</span> primary_voe_data <span class="sc">%&gt;%</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(subject, outcome_order,task, age_months, diff_log) <span class="sc">%&gt;%</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(task) <span class="sc">%&gt;%</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">diff_log =</span> <span class="fu">scale</span>(diff_log)) <span class="sc">%&gt;%</span>       <span class="co"># z-score within task</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">spread</span>(task, diff_log)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="co">#fit 1-factor CFA model</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>model_gen <span class="ot">&lt;-</span> <span class="st">'gen_factor =~ continuity + support + solidity + containment + reach + snack + drink + fairness'</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>fit1.lav <span class="ot">&lt;-</span> <span class="fu">cfa</span>(model_gen, <span class="at">missing =</span> <span class="st">"FIML"</span>, <span class="at">estimator =</span> <span class="st">"MLR"</span>, <span class="at">data =</span> dat.lav, <span class="at">std.lv =</span> <span class="cn">TRUE</span>)</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a><span class="co">#summarize original 1-factor model</span></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit1.lav)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6-21 ended normally after 17 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        24

  Number of observations                            86
  Number of missing patterns                        39

Model Test User Model:
                                              Standard      Scaled
  Test Statistic                                20.348      20.898
  Degrees of freedom                                20          20
  P-value (Chi-square)                           0.436       0.403
  Scaling correction factor                                  0.974
    Yuan-Bentler correction (Mplus variant)                       

Parameter Estimates:

  Standard errors                             Sandwich
  Information bread                           Observed
  Observed information based on                Hessian

Latent Variables:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
  gen_factor =~                                       
    continuity        0.249    0.178    1.398    0.162
    support           0.355    0.286    1.244    0.213
    solidity          0.530    0.194    2.732    0.006
    containment       0.627    0.167    3.759    0.000
    reach             0.429    0.209    2.050    0.040
    snack             0.488    0.273    1.786    0.074
    drink             0.405    0.192    2.107    0.035
    fairness          0.425    0.139    3.067    0.002

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .continuity        0.008    0.119    0.064    0.949
   .support          -0.010    0.124   -0.082    0.935
   .solidity         -0.018    0.118   -0.156    0.876
   .containment       0.020    0.124    0.160    0.873
   .reach             0.009    0.116    0.076    0.940
   .snack            -0.033    0.126   -0.261    0.794
   .drink             0.000    0.114    0.000    1.000
   .fairness          0.003    0.119    0.023    0.982

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)
   .continuity        0.925    0.198    4.683    0.000
   .support           0.864    0.222    3.894    0.000
   .solidity          0.721    0.214    3.368    0.001
   .containment       0.619    0.229    2.703    0.007
   .reach             0.809    0.198    4.081    0.000
   .snack             0.757    0.218    3.465    0.001
   .drink             0.822    0.229    3.588    0.000
   .fairness          0.803    0.202    3.973    0.000
    gen_factor        1.000                           </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fitMeasures</span>(fit1.lav, <span class="fu">c</span>(<span class="st">"cfi.robust"</span>, <span class="st">"tli.robust"</span>, <span class="st">"rmsea.robust"</span>, <span class="st">"srmr"</span>, <span class="st">"aic"</span>, <span class="st">"bic"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  cfi.robust   tli.robust rmsea.robust         srmr          aic          bic 
       0.981        0.974        0.023        0.092     1561.576     1620.480 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co">#semTools::reliability(fit1.lav, what = c("alpha", "omega", "ave"))</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="mimic-model" class="level2">
<h2 class="anchored" data-anchor-id="mimic-model">1. MIMIC model</h2>
<p>I next fit a “MIMIC” model, in which I fit the same CFA/ measurement model, and add a structural model in which outcome_order predicts the latent factor. To the extent to which outcome order explains most (if not all) of the variance in the latent factor, this suggests that the latent factor (interpreted as a “general surprise” factor) is better interpreted as an “assigned order” factor. <strong>The upshot of this model is that outcome order explains ~85% of the variance in the latent “domain-general surprise sensitivity”.</strong> In other words, this model confirms that the latent factor is best understood as an “assigned order” factor.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>model_mimic <span class="ot">&lt;-</span> <span class="st">'</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="st">  gen_factor =~ continuity + support + solidity + containment + reach + snack + drink + fairness</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="st">  gen_factor ~ outcome_order</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="st">'</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>fit_mimic <span class="ot">&lt;-</span> <span class="fu">sem</span>(model_mimic, <span class="at">data =</span> dat.lav, <span class="at">estimator =</span> <span class="st">"MLR"</span>, <span class="at">missing =</span> <span class="st">"fiml"</span>)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_mimic, <span class="at">standardized =</span> <span class="cn">TRUE</span>, <span class="at">rsquare =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6-21 ended normally after 72 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        25

  Number of observations                            86
  Number of missing patterns                        39

Model Test User Model:
                                              Standard      Scaled
  Test Statistic                                28.110      27.730
  Degrees of freedom                                27          27
  P-value (Chi-square)                           0.405       0.425
  Scaling correction factor                                  1.014
    Yuan-Bentler correction (Mplus variant)                       

Parameter Estimates:

  Standard errors                             Sandwich
  Information bread                           Observed
  Observed information based on                Hessian

Latent Variables:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  gen_factor =~                                                         
    continuity        1.000                               0.249    0.251
    support           1.863    1.088    1.712    0.087    0.464    0.466
    solidity          1.810    1.026    1.764    0.078    0.451    0.454
    containment       1.838    1.090    1.686    0.092    0.458    0.459
    reach             1.993    1.141    1.746    0.081    0.497    0.500
    snack             1.048    0.722    1.451    0.147    0.261    0.263
    drink             1.958    1.154    1.697    0.090    0.488    0.491
    fairness          2.001    1.134    1.764    0.078    0.499    0.501

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  gen_factor ~                                                          
    outcome_order     0.459    0.244    1.879    0.060    1.840    0.920

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
   .continuity       -0.677    0.375   -1.806    0.071   -0.677   -0.681
   .support          -1.318    0.366   -3.600    0.000   -1.318   -1.325
   .solidity         -1.226    0.323   -3.791    0.000   -1.226   -1.234
   .containment      -1.235    0.339   -3.643    0.000   -1.235   -1.238
   .reach            -1.341    0.344   -3.895    0.000   -1.341   -1.351
   .snack            -0.744    0.313   -2.375    0.018   -0.744   -0.750
   .drink            -1.330    0.327   -4.073    0.000   -1.330   -1.338
   .fairness         -1.340    0.312   -4.296    0.000   -1.340   -1.346

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
   .continuity        0.925    0.189    4.893    0.000    0.925    0.937
   .support           0.774    0.144    5.395    0.000    0.774    0.782
   .solidity          0.785    0.172    4.556    0.000    0.785    0.794
   .containment       0.786    0.163    4.822    0.000    0.786    0.789
   .reach             0.738    0.141    5.237    0.000    0.738    0.750
   .snack             0.917    0.340    2.698    0.007    0.917    0.931
   .drink             0.751    0.194    3.877    0.000    0.751    0.759
   .fairness          0.742    0.184    4.031    0.000    0.742    0.749
   .gen_factor        0.010    0.015    0.628    0.530    0.153    0.153

R-Square:
                   Estimate
    continuity        0.063
    support           0.218
    solidity          0.206
    containment       0.211
    reach             0.250
    snack             0.069
    drink             0.241
    fairness          0.251
    gen_factor        0.847</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lavInspect</span>(fit_mimic, <span class="st">"rsquare"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> continuity     support    solidity containment       reach       snack 
      0.063       0.218       0.206       0.211       0.250       0.069 
      drink    fairness  gen_factor 
      0.241       0.251       0.847 </code></pre>
</div>
</div>
</section>
<section id="residualized-model" class="level2">
<h2 class="anchored" data-anchor-id="residualized-model">2. Residualized model</h2>
<p>An alternate way to dig into the effect of outcome order is to try to remove the effect of outcome order on looking on each task (via residualizing), and then refit the CFA model on residualized looking (i.e., after accounting for outcome order). I fit this model below. The model technically converges, but the general factor variance is now basically indistinguishable from zero (.001, 95% CI [-.029, .032]). The factor laodings are now all over the place - I think this is just a consequence of the shared variance being so, so small (so now the factor loading estimates are super unstable). <strong>The upshot seems to be that we can’t successfully identify a common factor after partialling out the effect of infants’ assigned order on looking time differences.</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co">#create a dataset</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>df_resid <span class="ot">&lt;-</span> dat.lav <span class="sc">%&gt;%</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">c</span>(continuity, support, solidity, containment, reach, snack, drink, fairness),</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>                <span class="sc">~</span> <span class="fu">resid</span>(<span class="fu">lm</span>(.x <span class="sc">~</span> outcome_order, <span class="at">data =</span> dat.lav, <span class="at">na.action =</span> na.exclude)),</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">.names =</span> <span class="st">"{.col}_r"</span>))</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="co">#fit CFA model</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>model_resid <span class="ot">&lt;-</span> <span class="st">'</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a><span class="st">  gen_factor =~ continuity_r + support_r + solidity_r + containment_r + reach_r + snack_r + drink_r + fairness_r</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a><span class="st">'</span></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>fit_resid <span class="ot">&lt;-</span> <span class="fu">cfa</span>(model_resid, <span class="at">data =</span> df_resid, <span class="at">estimator =</span> <span class="st">"MLR"</span>, <span class="at">missing =</span> <span class="st">"fiml"</span>)</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a><span class="co">#inspect model/fit results</span></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_resid, <span class="at">fit.measures =</span> <span class="cn">TRUE</span>, <span class="at">standardized =</span> <span class="cn">TRUE</span>,<span class="at">rsquare=</span><span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6-21 ended normally after 154 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        24

  Number of observations                            86
  Number of missing patterns                        39

Model Test User Model:
                                              Standard      Scaled
  Test Statistic                                14.353      17.246
  Degrees of freedom                                20          20
  P-value (Chi-square)                           0.812       0.637
  Scaling correction factor                                  0.832
    Yuan-Bentler correction (Mplus variant)                       

Model Test Baseline Model:

  Test statistic                                28.707      28.426
  Degrees of freedom                                28          28
  P-value                                        0.427       0.442
  Scaling correction factor                                  1.010

User Model versus Baseline Model:

  Comparative Fit Index (CFI)                    1.000       1.000
  Tucker-Lewis Index (TLI)                      12.180      10.040
                                                                  
  Robust Comparative Fit Index (CFI)                         1.000
  Robust Tucker-Lewis Index (TLI)                            2.625

Loglikelihood and Information Criteria:

  Loglikelihood user model (H0)               -720.820    -720.820
  Scaling correction factor                                  1.444
      for the MLR correction                                      
  Loglikelihood unrestricted model (H1)       -713.644    -713.644
  Scaling correction factor                                  1.166
      for the MLR correction                                      
                                                                  
  Akaike (AIC)                                1489.640    1489.640
  Bayesian (BIC)                              1548.544    1548.544
  Sample-size adjusted Bayesian (SABIC)       1472.823    1472.823

Root Mean Square Error of Approximation:

  RMSEA                                          0.000       0.000
  90 Percent confidence interval - lower         0.000       0.000
  90 Percent confidence interval - upper         0.059       0.085
  P-value H_0: RMSEA &lt;= 0.050                    0.925       0.797
  P-value H_0: RMSEA &gt;= 0.080                    0.015       0.064
                                                                  
  Robust RMSEA                                               0.000
  90 Percent confidence interval - lower                     0.000
  90 Percent confidence interval - upper                     0.096
  P-value H_0: Robust RMSEA &lt;= 0.050                         0.809
  P-value H_0: Robust RMSEA &gt;= 0.080                         0.090

Standardized Root Mean Square Residual:

  SRMR                                           0.076       0.076

Parameter Estimates:

  Standard errors                             Sandwich
  Information bread                           Observed
  Observed information based on                Hessian

Latent Variables:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  gen_factor =~                                                         
    continuity_r      1.000                               0.036    0.038
    support_r        -4.126   24.454   -0.169    0.866   -0.150   -0.168
    solidity_r       16.812   92.297    0.182    0.855    0.613    0.653
    containment_r    11.565   71.525    0.162    0.872    0.422    0.465
    reach_r          -6.480   41.423   -0.156    0.876   -0.236   -0.268
    snack_r          14.696   94.024    0.156    0.876    0.536    0.553
    drink_r          -0.179    3.783   -0.047    0.962   -0.007   -0.007
    fairness_r        4.293   31.811    0.135    0.893    0.156    0.179

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
   .continuity_r     -0.000    0.118   -0.002    0.998   -0.000   -0.000
   .support_r         0.000    0.110    0.002    0.998    0.000    0.000
   .solidity_r       -0.050    0.107   -0.471    0.638   -0.050   -0.053
   .containment_r     0.039    0.109    0.359    0.720    0.039    0.043
   .reach_r           0.006    0.104    0.054    0.957    0.006    0.006
   .snack_r          -0.008    0.113   -0.066    0.947   -0.008   -0.008
   .drink_r           0.000    0.103    0.000    1.000    0.000    0.000
   .fairness_r       -0.004    0.107   -0.040    0.968   -0.004   -0.005

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
   .continuity_r      0.934    0.185    5.043    0.000    0.934    0.999
   .support_r         0.783    0.153    5.131    0.000    0.783    0.972
   .solidity_r        0.505    0.415    1.215    0.224    0.505    0.573
   .containment_r     0.644    0.181    3.557    0.000    0.644    0.784
   .reach_r           0.722    0.153    4.734    0.000    0.722    0.928
   .snack_r           0.652    0.191    3.415    0.001    0.652    0.694
   .drink_r           0.788    0.193    4.073    0.000    0.788    1.000
   .fairness_r        0.741    0.152    4.866    0.000    0.741    0.968
    gen_factor        0.001    0.016    0.086    0.932    1.000    1.000

R-Square:
                   Estimate
    continuity_r      0.001
    support_r         0.028
    solidity_r        0.427
    containment_r     0.216
    reach_r           0.072
    snack_r           0.306
    drink_r           0.000
    fairness_r        0.032</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fitMeasures</span>(fit_resid, <span class="fu">c</span>(<span class="st">"cfi.robust"</span>, <span class="st">"tli.robust"</span>, <span class="st">"rmsea.robust"</span>, <span class="st">"srmr"</span>, <span class="st">"aic"</span>, <span class="st">"bic"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  cfi.robust   tli.robust rmsea.robust         srmr          aic          bic 
       1.000        2.625        0.000        0.076     1489.640     1548.544 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">parameterEstimates</span>(fit_resid) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(lhs <span class="sc">==</span> <span class="st">"gen_factor"</span>, op <span class="sc">==</span> <span class="st">"~~"</span>)  <span class="co"># factor variance</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         lhs op        rhs   est    se     z pvalue ci.lower ci.upper
1 gen_factor ~~ gen_factor 0.001 0.016 0.086  0.932   -0.029    0.032</code></pre>
</div>
</div>
</section>
<section id="predicting-estimated-latent-scores-from-outcome-order" class="level2">
<h2 class="anchored" data-anchor-id="predicting-estimated-latent-scores-from-outcome-order">3. Predicting estimated latent scores from outcome order</h2>
<p>Here, I add another (probably dispreferred, but perhaps simpler) way to interrogate the extent to which the latent factor reflects outcome order. I extract estimates of the latent factor for individuals from the original CFA model. I then predict these individual estimates from outcome order. The analysis again finds that assigned order explains a vast amount of the variance in the latent factor (r squared = 0.44). Note that the variance explained is at the same time substantially lower than for Approach 1 (0.44 vs.&nbsp;0.85). I think this makes sense from a psychometric perspective, however, because of attenuation bias due to measurement unreliability. The MIMIC model estimates the variance explained directly from the measurement model, whereas in the approach below, we are correlating outcome order with (noisy) estimates of the individual scores. Because reliability of the general surprise factor is modest/ medium (~.66, see estimate above), the R2 naturally shrinks due to the additional noise. I think the MIMIC model is probably strictly the better approach here, but I report all three approaches I tried for transparency/ to give a more complete picture.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co">#extract individual estimates of general factor scores from the CFA model</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>fs <span class="ot">&lt;-</span> <span class="fu">lavPredict</span>(fit1.lav, <span class="at">method =</span> <span class="st">"Bartlett"</span>)  <span class="co"># from the original CFA fit</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>dat.lav<span class="sc">$</span>gen_factor_score <span class="ot">&lt;-</span> fs[, <span class="st">"gen_factor"</span>]</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="co">#how much variation does outcome order explain?</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(gen_factor_score <span class="sc">~</span> outcome_order, <span class="at">data =</span> dat.lav))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = gen_factor_score ~ outcome_order, data = dat.lav)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.8524 -0.5447  0.0327  0.7137  1.8400 

Coefficients:
                         Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)               -0.8775     0.1502  -5.841 9.52e-08 ***
outcome_orderunexp_first   1.7416     0.2125   8.197 2.44e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9851 on 84 degrees of freedom
Multiple R-squared:  0.4444,    Adjusted R-squared:  0.4378 
F-statistic:  67.2 on 1 and 84 DF,  p-value: 2.44e-12</code></pre>
</div>
</div>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<p>Triangulating across three approaches, it appears clear that the estimated latent factor in the CFA analysis is largely driven by and almost entirely accounted for by infants’ assigned order (~85% of the variance in the MIMIC model; there is little to explain once outcome order is regressed out of looking).</p>
</section>
</section>
<section id="observation-3-correlations-do-not-generally-hold-when-outcome-order-is-taken-into-account" class="level1">
<h1>Observation 3: Correlations do not generally hold when outcome order is taken into account</h1>
<section id="original-correlations" class="level2">
<h2 class="anchored" data-anchor-id="original-correlations">Original Correlations</h2>
<p>First, I reproduce the correlation plots demonstrating the relationship between looking time differences for social tasks vs.&nbsp;physical tasks, reported in the original paper (Figure 3).</p>
<p>Two notes:</p>
<ul>
<li><p>the median age is reported as 17.9 months in the paper, but I get 20.3 months (also when I run the original script or when I just inspect the primary_voe_data object post exclusions).</p></li>
<li><p>It appears that some additional data might have been excluded to create the exact plots in Figure 3. Or it looks like some points might be cut off in the Figures in the paper? I couldn’t track down which data might be excluded based on the scripts provided.</p></li>
</ul>
<p>Regardless, the general patterns hold true:</p>
<ul>
<li><p>There is an overall correlation of the VOE effects for the social vs.&nbsp;the physical domain.</p></li>
<li><p>Both younger and older infants show evidence of a correlation, but the correlation becomes much stronger for older infants.</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co">#data approach from the paper (adding outcome order)</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>dat.cross <span class="ot">&lt;-</span> primary_voe_data <span class="sc">%&gt;%</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(subject, age_months,outcome_order,domain) <span class="sc">%&gt;%</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">diff.m =</span> <span class="fu">mean</span>(diff_log, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">spread</span>(domain, diff.m) <span class="sc">%&gt;%</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>() <span class="sc">%&gt;%</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">age.z    =</span> <span class="fu">scale</span>(age_months),</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">physical =</span> <span class="fu">scale</span>(physical),</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">social   =</span> <span class="fu">scale</span>(social)</span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>  ) </span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>median_age <span class="ot">&lt;-</span> <span class="fu">median</span>(dat.cross<span class="sc">$</span>age_months)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true" href="">Overall</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false" href="">Younger Infants</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-3" role="tab" aria-controls="tabset-2-3" aria-selected="false" href="">Older Infants</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>overall <span class="ot">&lt;-</span> dat.cross <span class="sc">%&gt;%</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">scale</span>(physical), <span class="at">y =</span> social)) <span class="sc">+</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"blue2"</span>) <span class="sc">+</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">'lm'</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"blue2"</span>) <span class="sc">+</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Physical Surprise Scores"</span>, <span class="at">y =</span> <span class="st">"Social Surprise Scores"</span>) <span class="sc">+</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">aspect.ratio =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="sc">-</span><span class="fl">2.5</span>, <span class="fl">2.5</span>) <span class="sc">+</span> <span class="fu">ylim</span>(<span class="sc">-</span><span class="fl">3.5</span>,<span class="fl">3.5</span>)</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>overall</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="domain_general_voe_reanalysis_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Younger infants (&lt; median age)</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>younger <span class="ot">&lt;-</span> dat.cross <span class="sc">%&gt;%</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(age_months <span class="sc">&lt;=</span> median_age) <span class="sc">%&gt;%</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">scale</span>(physical), <span class="at">y =</span> social)) <span class="sc">+</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"blue2"</span>) <span class="sc">+</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">'lm'</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"blue2"</span>) <span class="sc">+</span></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Physical Surprise Scores"</span>, <span class="at">y =</span> <span class="st">"Social Surprise Scores"</span>) <span class="sc">+</span></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">aspect.ratio =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="sc">-</span><span class="fl">2.5</span>, <span class="fl">2.5</span>) <span class="sc">+</span> <span class="fu">ylim</span>(<span class="sc">-</span><span class="fl">3.5</span>, <span class="fl">3.5</span>) <span class="co">#scaling issue???// exclusions different from paper?</span></span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>younger</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="domain_general_voe_reanalysis_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-2-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-3-tab">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Older infants (&gt; median age)</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>older <span class="ot">&lt;-</span> dat.cross <span class="sc">%&gt;%</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(age_months <span class="sc">&gt;</span> median_age) <span class="sc">%&gt;%</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">scale</span>(physical), <span class="at">y =</span> <span class="fu">scale</span>(social))) <span class="sc">+</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"blue3"</span>) <span class="sc">+</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">'lm'</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"blue3"</span>) <span class="sc">+</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Physical Surprise Scores"</span>, <span class="at">y =</span> <span class="st">"Social Surprise Scores"</span>) <span class="sc">+</span></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">aspect.ratio =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="sc">-</span><span class="fl">2.5</span>, <span class="fl">2.5</span>) <span class="sc">+</span> <span class="fu">ylim</span>(<span class="sc">-</span><span class="fl">3.5</span>, <span class="fl">3.5</span>)</span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>older</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="domain_general_voe_reanalysis_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="correlations-split-by-outcome-order" class="level2">
<h2 class="anchored" data-anchor-id="correlations-split-by-outcome-order">Correlations split by outcome order</h2>
<p>First, observe the distribution of expected-first vs.&nbsp;unexpected-first infants in the overall correlation plot. We can see that at least a large amount of the covariance is due to order: expected-first infants show lower looking time differences (longer looking to the expected trial, which is their first trial) in both domains, unexpected-first infants show higher looking time differences (longer looking to the unexpected trial, which is their first trial).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>overall_order_color <span class="ot">&lt;-</span> dat.cross <span class="sc">%&gt;%</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">scale</span>(physical), <span class="at">y =</span> social,<span class="at">color=</span>outcome_order)) <span class="sc">+</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">'lm'</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"blue2"</span>) <span class="sc">+</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Physical Surprise Scores"</span>, <span class="at">y =</span> <span class="st">"Social Surprise Scores"</span>) <span class="sc">+</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">aspect.ratio =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="sc">-</span><span class="fl">2.5</span>, <span class="fl">2.5</span>) <span class="sc">+</span> <span class="fu">ylim</span>(<span class="sc">-</span><span class="fl">3.5</span>,<span class="fl">3.5</span>)<span class="sc">+</span></span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="fu">c</span>(<span class="fl">0.2</span>,<span class="fl">0.9</span>))</span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>overall_order_color</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="domain_general_voe_reanalysis_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Now, I look at the correlations splitting by the (assigned) expected-first or unexpected-first order. Are there any correlations after removing variance (in the surprisal score) due to assigned order? There appears to be much less systematic variance after splitting the data. There is perhaps some sign of a correlation among older infants in the unexpected-first group (r=.52), but not in the expected-first group. Younger infants show no evidence of systematic covariation.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true" href="">Overall</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false" href="">Younger Infants</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-3" role="tab" aria-controls="tabset-3-3" aria-selected="false" href="">Older Infants</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>overall_order_split <span class="ot">&lt;-</span> dat.cross <span class="sc">%&gt;%</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">scale</span>(physical), <span class="at">y =</span> social)) <span class="sc">+</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"blue2"</span>) <span class="sc">+</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">'lm'</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"blue2"</span>) <span class="sc">+</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Physical Surprise Scores"</span>, <span class="at">y =</span> <span class="st">"Social Surprise Scores"</span>) <span class="sc">+</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">aspect.ratio =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="sc">-</span><span class="fl">2.5</span>, <span class="fl">2.5</span>) <span class="sc">+</span> <span class="fu">ylim</span>(<span class="sc">-</span><span class="fl">3.5</span>,<span class="fl">3.5</span>)<span class="sc">+</span></span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>outcome_order)</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>overall_order_split</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="domain_general_voe_reanalysis_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Younger infants (&lt; median age)</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>younger_order_split <span class="ot">&lt;-</span> dat.cross <span class="sc">%&gt;%</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(age_months <span class="sc">&lt;=</span> median_age) <span class="sc">%&gt;%</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">scale</span>(physical), <span class="at">y =</span> social)) <span class="sc">+</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"blue2"</span>) <span class="sc">+</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">'lm'</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"blue2"</span>) <span class="sc">+</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Physical Surprise Scores"</span>, <span class="at">y =</span> <span class="st">"Social Surprise Scores"</span>) <span class="sc">+</span></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">aspect.ratio =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="sc">-</span><span class="fl">2.5</span>, <span class="fl">2.5</span>) <span class="sc">+</span> <span class="fu">ylim</span>(<span class="sc">-</span><span class="fl">3.5</span>, <span class="fl">3.5</span>) <span class="sc">+</span></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>outcome_order)</span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>younger_order_split</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="domain_general_voe_reanalysis_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co">#expected first</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(<span class="fu">filter</span>(dat.cross,age_months<span class="sc">&lt;=</span>median_age<span class="sc">&amp;</span>outcome_order<span class="sc">==</span><span class="st">"exp_first"</span>)<span class="sc">$</span>physical,<span class="fu">filter</span>(dat.cross,age_months<span class="sc">&lt;=</span>median_age<span class="sc">&amp;</span>outcome_order<span class="sc">==</span><span class="st">"exp_first"</span>)<span class="sc">$</span>social)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  filter(dat.cross, age_months &lt;= median_age &amp; outcome_order == "exp_first")$physical and filter(dat.cross, age_months &lt;= median_age &amp; outcome_order == "exp_first")$social
t = -0.39843, df = 18, p-value = 0.695
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.5147228  0.3640862
sample estimates:
       cor 
-0.0934987 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co">#unexpected first</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(<span class="fu">filter</span>(dat.cross,age_months<span class="sc">&lt;=</span>median_age<span class="sc">&amp;</span>outcome_order<span class="sc">==</span><span class="st">"unexp_first"</span>)<span class="sc">$</span>physical,<span class="fu">filter</span>(dat.cross,age_months<span class="sc">&lt;=</span>median_age<span class="sc">&amp;</span>outcome_order<span class="sc">==</span><span class="st">"unexp_first"</span>)<span class="sc">$</span>social)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  filter(dat.cross, age_months &lt;= median_age &amp; outcome_order == "unexp_first")$physical and filter(dat.cross, age_months &lt;= median_age &amp; outcome_order == "unexp_first")$social
t = 0.22512, df = 22, p-value = 0.824
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.3624657  0.4427746
sample estimates:
       cor 
0.04794083 </code></pre>
</div>
</div>
</div>
<div id="tabset-3-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-3-tab">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Older infants (&gt; median age)</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>older_order_split <span class="ot">&lt;-</span> dat.cross <span class="sc">%&gt;%</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(age_months <span class="sc">&gt;</span> median_age) <span class="sc">%&gt;%</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">scale</span>(physical), <span class="at">y =</span> <span class="fu">scale</span>(social))) <span class="sc">+</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"blue3"</span>) <span class="sc">+</span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">'lm'</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"blue3"</span>) <span class="sc">+</span></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Physical Surprise Scores"</span>, <span class="at">y =</span> <span class="st">"Social Surprise Scores"</span>) <span class="sc">+</span></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">aspect.ratio =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="sc">-</span><span class="fl">2.5</span>, <span class="fl">2.5</span>) <span class="sc">+</span> <span class="fu">ylim</span>(<span class="sc">-</span><span class="fl">3.5</span>, <span class="fl">3.5</span>)<span class="sc">+</span></span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>outcome_order)</span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a>older_order_split</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="domain_general_voe_reanalysis_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co">#expected first</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(<span class="fu">filter</span>(dat.cross,age_months <span class="sc">&gt;</span> median_age<span class="sc">&amp;</span>outcome_order<span class="sc">==</span><span class="st">"exp_first"</span>)<span class="sc">$</span>physical,<span class="fu">filter</span>(dat.cross,age_months <span class="sc">&gt;</span> median_age<span class="sc">&amp;</span>outcome_order<span class="sc">==</span><span class="st">"exp_first"</span>)<span class="sc">$</span>social)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  filter(dat.cross, age_months &gt; median_age &amp; outcome_order == "exp_first")$physical and filter(dat.cross, age_months &gt; median_age &amp; outcome_order == "exp_first")$social
t = 1.0641, df = 21, p-value = 0.2994
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.2051348  0.5839498
sample estimates:
      cor 
0.2261937 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co">#unexpected first</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(<span class="fu">filter</span>(dat.cross,age_months <span class="sc">&gt;</span> median_age<span class="sc">&amp;</span>outcome_order<span class="sc">==</span><span class="st">"unexp_first"</span>)<span class="sc">$</span>physical,<span class="fu">filter</span>(dat.cross,age_months <span class="sc">&gt;</span> median_age<span class="sc">&amp;</span>outcome_order<span class="sc">==</span><span class="st">"unexp_first"</span>)<span class="sc">$</span>social)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  filter(dat.cross, age_months &gt; median_age &amp; outcome_order == "unexp_first")$physical and filter(dat.cross, age_months &gt; median_age &amp; outcome_order == "unexp_first")$social
t = 2.5749, df = 17, p-value = 0.01968
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.09939423 0.79308985
sample estimates:
      cor 
0.5296902 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="no-significant-effect-after-controlling-for-outcome-order" class="level2">
<h2 class="anchored" data-anchor-id="no-significant-effect-after-controlling-for-outcome-order">No significant effect after controlling for outcome order</h2>
<p>When I fit the regression model predicting physical from social task looking and its interaction with age, but control for outcome order, there is no longer an overall significant effect of social task on physical task looking. The interaction with age is still significant (but a small effect). Outcome order explains a huge proportion of the variance.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>mod_int_control <span class="ot">&lt;-</span> <span class="fu">lm</span>(physical <span class="sc">~</span> social <span class="sc">*</span> age.z <span class="sc">+</span> outcome_order, <span class="at">data =</span> dat.cross)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_int_control)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = physical ~ social * age.z + outcome_order, data = dat.cross)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.94701 -0.53269 -0.06734  0.53819  1.49749 

Coefficients:
                         Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)              -0.41587    0.14095  -2.950 0.004148 ** 
social                    0.20212    0.11006   1.836 0.069959 .  
age.z                    -0.06556    0.08800  -0.745 0.458441    
outcome_orderunexp_first  0.85523    0.22171   3.857 0.000229 ***
social:age.z              0.23971    0.10352   2.315 0.023117 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.7964 on 81 degrees of freedom
Multiple R-squared:  0.3955,    Adjusted R-squared:  0.3657 
F-statistic: 13.25 on 4 and 81 DF,  p-value: 2.378e-08</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>anova_mod_int_control <span class="ot">&lt;-</span> <span class="fu">Anova</span>(mod_int_control, <span class="at">type=</span><span class="dv">3</span>)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>anova_mod_int_control</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type III tests)

Response: physical
              Sum Sq Df F value   Pr(&gt;F)    
(Intercept)    5.522  1  8.7052 0.004148 ** 
social         2.139  1  3.3726 0.069959 .  
age.z          0.352  1  0.5550 0.458441    
outcome_order  9.438  1 14.8794 0.000229 ***
social:age.z   3.401  1  5.3614 0.023117 *  
Residuals     51.379 81                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
</section>
<section id="other-concerns" class="level1">
<h1>Other concerns</h1>
<section id="only-2-of-the-8-voe-tasks-show-a-significant-voe-effect" class="level2">
<h2 class="anchored" data-anchor-id="only-2-of-the-8-voe-tasks-show-a-significant-voe-effect">Only 2 of the 8 VOE tasks show a significant VOE effect</h2>
<p>Only 2 of the 8 VOE tasks show a statistically significant VOE effect. The corresponding t-tests are run in the script on OSF (great!), but they are not reported in the paper. Below is a plot showing the distribution of looking time difference scores for each task.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co">#compute average looking time difference by task, with 95% CIs</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>summarized_data <span class="ot">&lt;-</span> primary_voe_data <span class="sc">%&gt;%</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(domain,task) <span class="sc">%&gt;%</span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">N=</span><span class="fu">n</span>(),</span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_diff =</span> <span class="fu">mean</span>(diff_log, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">se_diff =</span> <span class="fu">sd</span>(diff_log, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">/</span> <span class="fu">sqrt</span>(N),</span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">ci_diff =</span> <span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="at">df =</span> N <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> se_diff,</span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-11"><a href="#cb51-11" aria-hidden="true" tabindex="-1"></a><span class="co">#plot</span></span>
<span id="cb51-12"><a href="#cb51-12" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(summarized_data,<span class="fu">aes</span>(<span class="at">x=</span><span class="fu">reorder</span>(task,mean_diff),mean_diff,<span class="at">fill=</span>domain, <span class="at">color=</span>domain))<span class="sc">+</span></span>
<span id="cb51-13"><a href="#cb51-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">data=</span>primary_voe_data,<span class="fu">aes</span>(<span class="at">x=</span><span class="fu">reorder</span>(task,diff_log,mean),<span class="at">y=</span>diff_log),<span class="at">stat=</span><span class="st">"identity"</span>, <span class="at">size=</span><span class="dv">1</span>,<span class="at">alpha=</span><span class="fl">0.1</span>,<span class="at">height=</span><span class="dv">0</span>,<span class="at">width=</span><span class="fl">0.1</span>)<span class="sc">+</span></span>
<span id="cb51-14"><a href="#cb51-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>(<span class="at">data=</span>primary_voe_data,<span class="fu">aes</span>(<span class="at">x=</span><span class="fu">reorder</span>(task,diff_log,mean),<span class="at">y=</span>diff_log),<span class="at">width=</span><span class="fl">0.5</span>,<span class="at">fill=</span><span class="cn">NA</span>)<span class="sc">+</span></span>
<span id="cb51-15"><a href="#cb51-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">stat=</span><span class="st">"identity"</span>, <span class="at">size=</span><span class="dv">3</span>)<span class="sc">+</span></span>
<span id="cb51-16"><a href="#cb51-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin=</span>mean_diff<span class="sc">-</span>ci_diff,<span class="at">ymax=</span>mean_diff<span class="sc">+</span>ci_diff),<span class="at">width=</span><span class="dv">0</span>)<span class="sc">+</span></span>
<span id="cb51-17"><a href="#cb51-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept=</span><span class="dv">0</span>,<span class="at">linetype=</span><span class="st">"dashed"</span>)<span class="sc">+</span></span>
<span id="cb51-18"><a href="#cb51-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>domain, <span class="at">scales=</span><span class="st">"free_x"</span>)<span class="sc">+</span></span>
<span id="cb51-19"><a href="#cb51-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Task"</span>,<span class="at">y=</span><span class="st">"Log Looking Time Difference (Unexpected-Expected)"</span>)<span class="sc">+</span></span>
<span id="cb51-20"><a href="#cb51-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()<span class="sc">+</span></span>
<span id="cb51-21"><a href="#cb51-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_brewer</span>(<span class="at">palette=</span><span class="st">"Set2"</span>)<span class="sc">+</span></span>
<span id="cb51-22"><a href="#cb51-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="domain_general_voe_reanalysis_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="bayesian-model-issues" class="level2">
<h2 class="anchored" data-anchor-id="bayesian-model-issues">Bayesian model issues</h2>
<section id="interpretation-of-interaction-as-a-main-effect" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-of-interaction-as-a-main-effect">Interpretation of interaction as a main effect</h3>
<p>The paper seems to describe a main effect of general surprise scores on broad exploration curiosity scores . E.g., on p.&nbsp;6: “As predicted, we observed a reliable relationship between infants’ general surprise responses and their later Broad Exploration; this effect was significantly affected by age.” Similarly in the discussion, the paper reads: “Infants’ surprise responses predicted their later Broad Exploration.” However, there is no main effect of surprise on broad exploration: there is only an interaction between age (at VOE task) and general surprise, as reported in Table 1. The general relationship between surprise and broad exploration is negative and non-significant. The plot below illustrates this point.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co">#create the dataset used in the brms model</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>emcs_raw <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="fu">here</span>(<span class="st">"data"</span>,<span class="st">"emcs_raw.csv"</span>))</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>dat.brms <span class="ot">&lt;-</span> <span class="fu">left_join</span>(primary_voe_data, emcs_raw, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"subject"</span> <span class="ot">=</span> <span class="st">"subj"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">sociality         =</span> <span class="fu">scale</span>(emcs_soc),</span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">info_seeking      =</span> <span class="fu">scale</span>(emcs_seek),</span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">broad_exploration =</span> <span class="fu">scale</span>(emcs_exp),</span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">persistence       =</span> <span class="fu">scale</span>(emcs_per),</span>
<span id="cb52-11"><a href="#cb52-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">vocab_tot         =</span> <span class="fu">scale</span>(vocab_tot)</span>
<span id="cb52-12"><a href="#cb52-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb52-13"><a href="#cb52-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(subject, age_months, vocab_tot,</span>
<span id="cb52-14"><a href="#cb52-14" aria-hidden="true" tabindex="-1"></a>           broad_exploration, info_seeking,</span>
<span id="cb52-15"><a href="#cb52-15" aria-hidden="true" tabindex="-1"></a>           persistence, sociality, age_surv) <span class="sc">%&gt;%</span></span>
<span id="cb52-16"><a href="#cb52-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb52-17"><a href="#cb52-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">gen_factor =</span> <span class="fu">mean</span>(diff_log, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)  <span class="co"># average surprise score per subject</span></span>
<span id="cb52-18"><a href="#cb52-18" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb52-19"><a href="#cb52-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>() <span class="sc">%&gt;%</span></span>
<span id="cb52-20"><a href="#cb52-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb52-21"><a href="#cb52-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb52-22"><a href="#cb52-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">gen_factor   =</span> <span class="fu">scale</span>(gen_factor),</span>
<span id="cb52-23"><a href="#cb52-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_months.z =</span> <span class="fu">scale</span>(age_months),</span>
<span id="cb52-24"><a href="#cb52-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_surv.z   =</span> <span class="fu">scale</span>(age_surv)) <span class="sc">%&gt;%</span></span>
<span id="cb52-25"><a href="#cb52-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb52-26"><a href="#cb52-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_split    =</span> <span class="fu">ifelse</span>(age_months.z <span class="sc">&gt;</span> <span class="dv">0</span>, <span class="st">"older"</span>, <span class="st">"younger"</span>)</span>
<span id="cb52-27"><a href="#cb52-27" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb52-28"><a href="#cb52-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-29"><a href="#cb52-29" aria-hidden="true" tabindex="-1"></a><span class="co">#plot just the simple correlation of broad exploration and general surprise, then split by age</span></span>
<span id="cb52-30"><a href="#cb52-30" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(dat.brms,<span class="fu">aes</span>(gen_factor,broad_exploration))<span class="sc">+</span></span>
<span id="cb52-31"><a href="#cb52-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb52-32"><a href="#cb52-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>)<span class="sc">+</span></span>
<span id="cb52-33"><a href="#cb52-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"General Surprise Factor"</span>, <span class="at">y=</span> <span class="st">"Broad Exploration Score"</span>,<span class="at">title=</span><span class="st">"Overall"</span>)<span class="sc">+</span></span>
<span id="cb52-34"><a href="#cb52-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span>
<span id="cb52-35"><a href="#cb52-35" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="fu">filter</span>(dat.brms,age_split<span class="sc">==</span><span class="st">"younger"</span>),<span class="fu">aes</span>(gen_factor,broad_exploration))<span class="sc">+</span></span>
<span id="cb52-36"><a href="#cb52-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb52-37"><a href="#cb52-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>)<span class="sc">+</span></span>
<span id="cb52-38"><a href="#cb52-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"General Surprise Factor"</span>, <span class="at">y=</span> <span class="st">"Broad Exploration Score"</span>,<span class="at">title=</span><span class="st">"Younger Infants"</span>)<span class="sc">+</span></span>
<span id="cb52-39"><a href="#cb52-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span>
<span id="cb52-40"><a href="#cb52-40" aria-hidden="true" tabindex="-1"></a>p3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="fu">filter</span>(dat.brms,age_split<span class="sc">==</span><span class="st">"older"</span>),<span class="fu">aes</span>(gen_factor,broad_exploration))<span class="sc">+</span></span>
<span id="cb52-41"><a href="#cb52-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb52-42"><a href="#cb52-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>)<span class="sc">+</span></span>
<span id="cb52-43"><a href="#cb52-43" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"General Surprise Factor"</span>, <span class="at">y=</span> <span class="st">"Broad Exploration Score"</span>,<span class="at">title=</span><span class="st">"Older Infants"</span>)<span class="sc">+</span></span>
<span id="cb52-44"><a href="#cb52-44" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span>
<span id="cb52-45"><a href="#cb52-45" aria-hidden="true" tabindex="-1"></a>p1<span class="sc">+</span>p2<span class="sc">+</span>p3</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="domain_general_voe_reanalysis_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Note that even among older infants (median-split), there is no effect of “general surprise” on broad exploration (r=.24, non-significant).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(<span class="fu">filter</span>(dat.brms,age_split<span class="sc">==</span><span class="st">"older"</span>)<span class="sc">$</span>gen_factor, <span class="fu">filter</span>(dat.brms,age_split<span class="sc">==</span><span class="st">"older"</span>)<span class="sc">$</span>broad_exploration)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  filter(dat.brms, age_split == "older")$gen_factor and filter(dat.brms, age_split == "older")$broad_exploration
t = 1.3522, df = 31, p-value = 0.1861
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.1167735  0.5358880
sample estimates:
      cor 
0.2359965 </code></pre>
</div>
</div>
</section>
<section id="interaction-model-does-not-include-lower-order-effects" class="level3">
<h3 class="anchored" data-anchor-id="interaction-model-does-not-include-lower-order-effects">Interaction Model does not include lower-order effects</h3>
<p>An additional note is that I’m also worried about the specification of the Bayesian model predicting curiosity scores from general surprise. This also relates to the point above, because the interaction effect in the model can’t be interpreted as a “pure” interaction. The model attempts to interpret an age(voe) by general surprise interaction, but without including all lower-order effects, in particular the effect of age(voe). I suspect this decision was made because there are two age variables (age when the VOE session occurred and age at which the questionnaire was filled out), and this decision is to avoid including both age variables. But, the result is that the “interaction” effect is now a difficult-to-interpret mix of a main effect of age(voe) and an interaction effect.</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>